# Tensors

Tensors are a specialized data structure similar to arrays and matrics. It is used in PyTorch to encode the inputs and outputs of a model, as well as model's parameters.

Tensors are similar to Numpy's ndarrays, except that they can run on GPUs or other hardware accelerators. Both tensors and ndarrays can often share the same underlying memory, eliminating the need to copy data.

Tensors are also optimized for automatic differentiation.

In [1]:
import torch
import numpy as np

## Initializing a Tensor

In [2]:
'''
1. Directly from data - data type is automaticall inferred
'''

data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
'''
2. From a NumPy array
'''
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
'''
3. From another tensor
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden
'''
x_ones = torch.ones_like(x_data)  # retrains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8931, 0.0351],
        [0.5326, 0.3696]]) 



In [5]:
'''
4. With random or constant values:

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.
'''
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.0822, 0.6411, 0.6127],
        [0.2353, 0.3900, 0.5893]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored

In [6]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors